// <auto-generated />
using System;
using Dams.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dams.Web.Data.Migrations
{
    [DbContext(typeof(DamsDbContext))]
    partial class DamsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dams.Web.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AdminId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Admins_UserId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Dams.Web.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("SlotId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("AppointmentId");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("IX_Appointments_DoctorId");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_Appointments_PatientId");

                    b.HasIndex("SlotId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Appointments_SlotId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Appointments_Status");

                    b.ToTable("Appointments", t =>
                        {
                            t.HasCheckConstraint("CK_Appointments_Status", "[Status] IN ('Pending', 'Confirmed', 'Rejected', 'Cancelled', 'Completed')");
                        });
                });

            modelBuilder.Entity("Dams.Web.Models.AppointmentSlot", b =>
                {
                    b.Property<int>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlotId"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time(0)");

                    b.Property<bool>("IsBooked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SlotDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(0)");

                    b.HasKey("SlotId");

                    b.HasIndex("IsBooked")
                        .HasDatabaseName("IX_Slots_IsBooked");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("DoctorId", "SlotDate")
                        .HasDatabaseName("IX_Slots_DoctorId_Date");

                    b.HasIndex("DoctorId", "SlotDate", "StartTime")
                        .IsUnique()
                        .HasDatabaseName("UQ_Slots_Doctor_DateTime");

                    b.ToTable("AppointmentSlots", t =>
                        {
                            t.HasCheckConstraint("CK_Slots_TimeRange", "[StartTime] < [EndTime]");
                        });
                });

            modelBuilder.Entity("Dams.Web.Models.Clinic", b =>
                {
                    b.Property<int>("ClinicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClinicId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClinicName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ClinicId");

                    b.HasIndex("ClinicName")
                        .IsUnique()
                        .HasDatabaseName("UQ_Clinics_ClinicName");

                    b.ToTable("Clinics");

                    b.HasData(
                        new
                        {
                            ClinicId = 1,
                            Address = "10 Health Street",
                            City = "Cairo",
                            ClinicName = "DAMS Main Clinic",
                            PhoneNumber = "01000000000"
                        });
                });

            modelBuilder.Entity("Dams.Web.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<string>("Biography")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceYears")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ProfilePicturePath")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Qualifications")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DoctorId");

                    b.HasIndex("ClinicId")
                        .HasDatabaseName("IX_Doctors_ClinicId");

                    b.HasIndex("SpecializationId")
                        .HasDatabaseName("IX_Doctors_SpecializationId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Doctors_Status");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Doctors_UserId");

                    b.ToTable("Doctors", t =>
                        {
                            t.HasCheckConstraint("CK_Doctors_Experience", "[ExperienceYears] >= 0");

                            t.HasCheckConstraint("CK_Doctors_Status", "[Status] IN ('Active', 'Inactive')");
                        });

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            Biography = "Seed doctor account for phase 0 testing.",
                            ClinicId = 1,
                            ExperienceYears = 8,
                            Qualifications = "MBBCh, Cardiology specialist",
                            SpecializationId = 1,
                            Status = "Active",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Dams.Web.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Allergies")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BloodType")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("ChronicDiseases")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("ProfilePicturePath")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PatientId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Patients_UserId");

                    b.ToTable("Patients", t =>
                        {
                            t.HasCheckConstraint("CK_Patients_DOB", "[DateOfBirth] <= CAST(GETDATE() AS DATE)");
                        });

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            Allergies = "None",
                            BloodType = "O+",
                            ChronicDiseases = "None",
                            DateOfBirth = new DateTime(1995, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Dams.Web.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("ReviewId");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("IX_Reviews_DoctorId");

                    b.HasIndex("PatientId", "DoctorId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Reviews_Patient_Doctor");

                    b.ToTable("Reviews", t =>
                        {
                            t.HasCheckConstraint("CK_Reviews_Rating", "[Rating] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_Reviews_TextNotEmpty", "LEN(LTRIM(RTRIM([ReviewText]))) > 0");
                        });
                });

            modelBuilder.Entity("Dams.Web.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time(0)");

                    b.Property<int>("SlotDurationMinutes")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(0)");

                    b.HasKey("ScheduleId");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("IX_Schedules_DoctorId");

                    b.ToTable("Schedules", t =>
                        {
                            t.HasCheckConstraint("CK_Schedules_DayOfWeek", "[DayOfWeek] IN ('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday')");

                            t.HasCheckConstraint("CK_Schedules_SlotDuration", "[SlotDurationMinutes] IN (15, 30, 45, 60)");

                            t.HasCheckConstraint("CK_Schedules_TimeRange", "[StartTime] < [EndTime]");
                        });
                });

            modelBuilder.Entity("Dams.Web.Models.Specialization", b =>
                {
                    b.Property<int>("SpecializationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecializationId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SpecializationId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Specializations_Name");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            SpecializationId = 1,
                            Name = "Cardiology"
                        },
                        new
                        {
                            SpecializationId = 2,
                            Name = "Neurology"
                        },
                        new
                        {
                            SpecializationId = 3,
                            Name = "Pediatrics"
                        },
                        new
                        {
                            SpecializationId = 4,
                            Name = "Dermatology"
                        },
                        new
                        {
                            SpecializationId = 5,
                            Name = "Orthopedics"
                        });
                });

            modelBuilder.Entity("Dams.Web.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_Email");

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Gender", "[Gender] IN ('Male', 'Female')");

                            t.HasCheckConstraint("CK_Users_Role", "[Role] IN ('Patient', 'Doctor', 'Admin')");
                        });

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient@dams.local",
                            FullName = "Seed Patient",
                            Gender = "Female",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEE6ZSRSJhu5czumHnpiAh8kPdAXAX+E0Z3A+C+ErGmKZyrQecasvTvBNbWG32GUyzA==",
                            PhoneNumber = "01000000001",
                            Role = "Patient"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "doctor@dams.local",
                            FullName = "Seed Doctor",
                            Gender = "Male",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEE6ZSRSJhu5czumHnpiAh8kPdAXAX+E0Z3A+C+ErGmKZyrQecasvTvBNbWG32GUyzA==",
                            PhoneNumber = "01000000002",
                            Role = "Doctor"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@dams.local",
                            FullName = "Seed Admin",
                            Gender = "Male",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEE6ZSRSJhu5czumHnpiAh8kPdAXAX+E0Z3A+C+ErGmKZyrQecasvTvBNbWG32GUyzA==",
                            PhoneNumber = "01000000003",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("Dams.Web.Models.Admin", b =>
                {
                    b.HasOne("Dams.Web.Models.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("Dams.Web.Models.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Admins_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dams.Web.Models.Appointment", b =>
                {
                    b.HasOne("Dams.Web.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Appointments_Doctors");

                    b.HasOne("Dams.Web.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Appointments_Patients");

                    b.HasOne("Dams.Web.Models.AppointmentSlot", "Slot")
                        .WithOne("Appointment")
                        .HasForeignKey("Dams.Web.Models.Appointment", "SlotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Appointments_Slots");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("Dams.Web.Models.AppointmentSlot", b =>
                {
                    b.HasOne("Dams.Web.Models.Doctor", "Doctor")
                        .WithMany("AppointmentSlots")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Slots_Doctors");

                    b.HasOne("Dams.Web.Models.Schedule", "Schedule")
                        .WithMany("AppointmentSlots")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Slots_Schedules");

                    b.Navigation("Doctor");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Dams.Web.Models.Doctor", b =>
                {
                    b.HasOne("Dams.Web.Models.Clinic", "Clinic")
                        .WithMany("Doctors")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Doctors_Clinics");

                    b.HasOne("Dams.Web.Models.Specialization", "Specialization")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Doctors_Specializations");

                    b.HasOne("Dams.Web.Models.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("Dams.Web.Models.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Doctors_Users");

                    b.Navigation("Clinic");

                    b.Navigation("Specialization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dams.Web.Models.Patient", b =>
                {
                    b.HasOne("Dams.Web.Models.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("Dams.Web.Models.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Patients_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dams.Web.Models.Review", b =>
                {
                    b.HasOne("Dams.Web.Models.Doctor", "Doctor")
                        .WithMany("Reviews")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_Doctors");

                    b.HasOne("Dams.Web.Models.Patient", "Patient")
                        .WithMany("Reviews")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_Patients");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Dams.Web.Models.Schedule", b =>
                {
                    b.HasOne("Dams.Web.Models.Doctor", "Doctor")
                        .WithMany("Schedules")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Schedules_Doctors");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Dams.Web.Models.AppointmentSlot", b =>
                {
                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Dams.Web.Models.Clinic", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("Dams.Web.Models.Doctor", b =>
                {
                    b.Navigation("AppointmentSlots");

                    b.Navigation("Appointments");

                    b.Navigation("Reviews");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Dams.Web.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Dams.Web.Models.Schedule", b =>
                {
                    b.Navigation("AppointmentSlots");
                });

            modelBuilder.Entity("Dams.Web.Models.Specialization", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("Dams.Web.Models.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
